language: python
sudo: false
dist: trusty
cache: pip
env:
  global:
  - PYTHONFAULTHANDLER=x
  - secure: Zxhj02mKdnS7ZjHSq1zRPNjw6+7ya2i092gmSaM2/U0lJZEcXV1575SxWT/CCGDE3xsmpoBE/q4KG4pXNaZwZOX1cVCPD8o2pQoDcULi9CtpGyU266tjzHiHL5woF5NRJZjdIujebwz1CGWpRNNMuPRUtCFqHMI1NIbp3BUwxBtfplgZCns9C4kgrxF1H8s7pY6tq8PuNJwox5acdw6gGPyJzZiNXD54Xw1ZlLWa0PYisE71qtDRcQ4KmhAgiJiVKC1iL0Di0As3INKaKCTJfPH3KfwNVVbi9pwB2tA6+aUO7iXtmUkWGhzKaEhSKreTLbSpMsOdfXWPmRkb4+YBK+qtoXd3fOvMQ9MebjvBVCxipOS68H69Q7heMDHctxC2f+tNdXVe731TF5qw+HzmqOKfW/hgXn4uRwPmHDmhFegVW5WTmcLY8J6DikC2PnfSUZx6+xItxR/jjq98fpkmNqQacQfQb6Q4Uv+kA5igwn9AcytL8g6iHi/F9iPPhdhWi5ovAmuDY8bsnxcxxatucjzHEctiZcFuy0qEJoGjb9GwgF6wLdRTHRVXYyHUcWGdkJnK2wmcTa3a4LJNZSh0Y+OUK5MLc1GY1ts9okM01o8k74jBBUVMmPWcfrHIwqdqDJifQX75FY0hfyzjp0BLRW1mvmXpRMy66AOKLdhZ6E8=
matrix:
  include:
#    - python: '3.6'
#      env:
#        - TOXENV=.python36-urlfetch
#    - python: '3.6'
#      env:
#        - TOXENV=.python36-requests
#    - python: '3.6'
#      env:
#        - TOXENV=.python36-pycurl
#    - python: '3.6'
#      env:
#        - TOXENV=.python36
## PYTHON 3.7
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=.python37-urlfetch
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=.python37-requests
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=.python37-pycurl
      before_install:
        - sudo apt-get update
        - sudo apt install libgnutls28-dev
    - python: '3.7'
      dist: xenial
      sudo: true
      env:
        - TOXENV=.python37

## PYTHON 3.6 - OTHER TESTS
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=coverage

install:
- pip install -U tox codecov
script:
- tox -- -v
after_success:
- if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
